spring:
    security:
        oauth2:
            client:
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
                registration:
                    google:
                        client-id: ENC(q8dccSy11n8QZ+Ta/cwrgD4Yi8R55WMw/xQe1UPJKgna9ISn9to8PLlR3wLFF5QMEjxMMtSJCgHFKJfEKP68FNsIinbfgFr1hF8G3ta4cpKjxObIDV0hjw==)
                        client-secret: ENC(3wv9z1ZFyAnmFvfchBrVSAvm8CNl8zp7OyBdaCce7rm1vDD3iu/rk0oNTwIfRLLR)
                        scope: profile,email
                    kakao:
                        authorization-grant-type: authorization_code
                        client-authentication-method: POST
                        client-id: ENC(rQY937QYHi4w8qOPCBn44eHv6dko/rK6e7/DBNnC9btxNRtaoScg9U30sT5/AHMM)
                        client-name: Kakao
                        client-secret: ENC(R/YeN+oT2w7LXdZJnMtJLSdyRKTvddAJMO/o9fDu7qoLSJjRJ2kDYpfYB6E0n23l)
                        redirect-uri: http://bookhub.run/login/oauth2/code/kakao
                        scope: profile_nickname,account_email
                    naver:
                        authorization-grant-type: authorization_code
                        client-id: ENC(An+wD+NWFjKlcP4s2HID45QtViKiK8Sy2SHuz4efTpc=)
                        client-name: Naver
                        client-secret: ENC(JjW7eaulWfOLpCSlOm8OaT/odO8lEoC8)
                        redirect-uri: http://bookhub.run/login/oauth2/code/naver
                        scope: name,email
